name: Continue-on-error Test
on: [push, pull_request]

jobs:
  build:
    name: Test Action
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Exit
        run: exit 1
      - name: Python 1
        run: python src/pitching_machine.py
